import Head from 'next/head';

export default function Home() {
  const createNotification = async () => {
    /* 5秒待つ */
    // await new Promise((resolve) => setTimeout(resolve, 5000));

    console.log('Notification.permission: ', Notification.permission);

    if (Notification.permission === 'granted') {
      const noti = new Notification('Hello World!');
      // const noti = new Notification('Hello World!', {
      //   body: 'This is the body of the notification',
      //   icon: '/favicon.ico',
      // });
      console.log(noti);
    } else if (Notification.permission !== 'denied') {
      Notification.requestPermission().then((permission) => {
        if (permission === 'granted') {
          new Notification('Hello World!', {
            body: 'This is the body of the notification',
            icon: '/favicon.ico',
          });
        }
      });
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>Test Web Notification API</h1>
        <p>更新したよ</p>
        <div>
          <button onClick={createNotification}>Create Notification</button>
        </div>
      </main>
    </>
  );
}
